export var cardList = {
    data: function(){
        return {
            cardList: [
                { id: '00A', src: '10A', name: '唐僧' },
                { id: '00B', src: '10B', name: '唐僧' },
                { id: '00C', src: '10C', name: '唐僧' },
                { id: '00D', src: '10D', name: '唐僧' },
                { id: '01A', src: '2A', name: '妖怪2' },
                { id: '01B', src: '2B', name: '妖怪2' },
                { id: '01C', src: '2C', name: '妖怪2' },
                { id: '01D', src: '2D', name: '妖怪2' },
                { id: '02A', src: '4A', name: '妖怪4' },
                { id: '02B', src: '4B', name: '妖怪4' },
                { id: '02C', src: '4C', name: '妖怪4' },
                { id: '02D', src: '4D', name: '妖怪4' },
                { id: '03A', src: '6A', name: '妖怪6' },
                { id: '03B', src: '6B', name: '妖怪6' },
                { id: '03C', src: '6C', name: '妖怪6' },
                { id: '03D', src: '6D', name: '妖怪6' },
                { id: '04A', src: '7A', name: '妖怪7' },
                { id: '04B', src: '7B', name: '妖怪7' },
                { id: '04C', src: '7C', name: '妖怪7' },
                { id: '04D', src: '7D', name: '妖怪7' },
                { id: '05A', src: '9A', name: '妖怪9' },
                { id: '05B', src: '9B', name: '妖怪9' },
                { id: '05C', src: '9C', name: '妖怪9' },
                { id: '05D', src: '9D', name: '妖怪9' },
                { id: '06A', src: '11A', name: '妖怪J' },
                { id: '06B', src: '11B', name: '妖怪J' },
                { id: '06C', src: '11C', name: '妖怪J' },
                { id: '06D', src: '11D', name: '妖怪J' },
                { id: '07A', src: '12A', name: '妖怪Q' },
                { id: '07B', src: '12B', name: '妖怪Q' },
                { id: '07C', src: '12C', name: '妖怪Q' },
                { id: '07D', src: '12D', name: '妖怪Q' },
                { id: '08A', src: '13A', name: '妖怪K' },
                { id: '08B', src: '13B', name: '妖怪K' },
                { id: '08C', src: '13C', name: '妖怪K' },
                { id: '08D', src: '13D', name: '妖怪K' },
                { id: '09A', src: '1A', name: '妖怪A' },
                { id: '09B', src: '1B', name: '妖怪A' },
                { id: '09C', src: '1C', name: '妖怪A' },
                { id: '09D', src: '1D', name: '妖怪A' },
                { id: '10A', src: '3A', name: '沙僧' },
                { id: '10B', src: '3B', name: '沙僧' },
                { id: '10C', src: '3C', name: '沙僧' },
                { id: '10D', src: '3D', name: '沙僧' },
                { id: '11A', src: '8A', name: '八戒' },
                { id: '11B', src: '8B', name: '八戒' },
                { id: '11C', src: '8C', name: '八戒' },
                { id: '11D', src: '8D', name: '八戒' },
                { id: '12A', src: '5A', name: '悟空' },
                { id: '12B', src: '5B', name: '悟空' },
                { id: '12C', src: '5C', name: '悟空' },
                { id: '12D', src: '5D', name: '悟空' },
                { id: '13A', src: 'black-joker', name: '反弹' },
                { id: '13B', src: 'red-joker', name: '反弹' },
            ],
        }
    },
}